### ISSUE TITLE
Pointer `from`/ `to` generic return type mismatch.

### ISSUE THREAD

**Issue by mickare** [hashicorp/go-azure-helpers#159]
Hey, there is a return type mismatch of the pointer's generic `to` and `from` methods.

Example copied from the code
```go
// FromBool turns a boolean into a pointer to a boolean
func FromBool(input bool) *bool {
	...
}

// From is a generic function that returns the value of a pointer
// If the pointer is nil, a zero value for the underlying type of the pointer is returned.
func From[T any](input *T) (output T) {
	...
}
```

- `FromBool(...)` returns a pointer
- `From(...)`  returns the value

The same for the generic `To(...)`, etc...

**Comment by mickare** [comment]
Ping @jackofallops

**Comment by jackofallops** [comment]
Hi @mickare - Thanks for this issue. The `From` and `To` individual functions were previously the wrong way around.  Since a pointer is a location in memory, `From` retrieves the value from the location and `To` returns the location which points to the location of the value.

We will be deprecating and removing the older functions from this module in future as the dependency on them is phased out of the Azure providers.

We believe this is the correct orientation for these functions, and as such I'm going to close this issue.

Thanks again.

**Comment by mickare** [comment]
Hi @jackofallops , for me it's confusing because in Rust the logic is the other way around.

In Rust the current type (pointer) is created FROM another type-value.
And the current type (pointer) is converted INTO another type-value.

And when I read the code in the `azurerm` provider, I my head thinks it like this:
`pointer.From(some_value)`  ---> "Create a pointer from some value". 

I find it hard to think of `pointer.From(some_value)` as "Transform a pointer into some value". It is counter-intuitive (at least for me).
