### ISSUE TITLE
ComputeAccountSASToken is broken

### ISSUE THREAD

**Issue by seppi91** [hashicorp/go-azure-helpers#30]
Hi all,
I investigated into the issue I've created yesterday at terraform-azurerm provider https://github.com/terraform-providers/terraform-provider-azurerm/issues/3764 

For me it looks like the computation of the signed uri does not comply to the official docs of msft azure https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas

E.g. the field "srt" is not documented there but used in the resulting string.

**Comment by tombuildsstuff** [comment]
hey @seppi91 

Thanks for opening this issue.

The SDK method in question generates a SAS Token for a Storage Account ([as documented here](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-an-account-sas)) - rather than at a Service Level ([which is what's listed in that document](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas)) - which is why these are different.

There's a feature request tracking support for a Storage Account SAS Token [in this Github issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1868) which I'm going to close this issue in favour of - would you mind subscribing to that issue for updates?

Thanks!

**Comment by Sas002** [comment]
I have similar issue while deploying Azure Linux extension using terraform , generated Azure blob SAS token by terraform  never works but if I generate SAS token manually and copy into terraform code , everything works fine.   Reference : https://github.com/terraform-providers/terraform-provider-azurerm/issues/4336
