### ISSUE TITLE
Support for loading endpoints for custom Azure environments from a file

### ISSUE THREAD

**Issue by igal-s** [hashicorp/go-azure-helpers#54]
PR: #53 
Downstream issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6816

**Comment by tombuildsstuff** [comment]
hey @igal-s 

As mentioned in #53 - whilst one option for retrieving this information would be to retrieve this from a file on disk - after investigating this we've opted to instead pull this from the metadata endpoint of the Azure Instance which should return the information necessary here, albeit in a different way.

As such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #56 (which has since been merged) which adds support for retrieving this information from the metadata service - which once implemented in the Azure Provider should fix terraform-providers/terraform-provider-azurerm#6816

Thanks!
