### ISSUE TITLE
Authenticate as Az CLI + service principal

### ISSUE THREAD

**Issue by mikhailshilkov** [hashicorp/go-azure-helpers#82]
I can see this note [here](https://github.com/hashicorp/go-azure-helpers/blob/166ee52053a41ca9f6f28a1afe0afb77e62ce496/authentication/auth_method_azure_cli_token.go#L67):

> Authenticating as a Service Principal doesn't return all of the information we need for authentication purposes
> as such Service Principal authentication is supported using the specific auth method

We ran `az account show -o=json` and the output for a service principal seems to be similar to that of a user. Could you please elaborate on which information is missing? Is there a chance it was added since the original change?

Thank you.

**Comment by ToruMakabe** [comment]
+1

Due to this limitation, we cannot use Terraform with [OpenID Connect authentication](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#set-up-azure-login-with-openid-connect-authentication) on GitHub Actions. 

OIDC auth is extremely useful because we don't have to store client secret to GitHub, so could you please consider supporting for Az CLI + service principal auth?

**Comment by tombuildsstuff** [comment]
OIDC support is tracked in #91 - closing this issue in favour of that.

At this time unfortunately we have no plans to support using the Azure CLI with a Service Principal.
